### ISSUE TITLE
botnet.js makes weird arguments

### ISSUE THREAD

**Issue by AIT-OLPE** [jenheilemann/bitburner-scripts#3]
Hello,

On a successful "start" and "run" the following error msg gets thrown hundreds of times a second. On grow.js it takes argument 0 for sleep, and 1 for hostname. How come I get error messages that it used arg0 for hostname? When manually writing a script that kills all other scripts and spam clicking through all error messages I can check the script-history and see that the arguments are exactly the same on all of them and some seems to work. Is this some sort of overflow that can't fit in RAM and therefore gives an error message? It's the same for grow, hack, weaken exactly the same runtime error.

RUNTIME ERROR
grow.js@n00dles
Args: [102706.22572262463, "the-hub", 1640820219894]

grow: Invalid hostname or IP: 102706.22572262463

Stack:
grow.js:L2@Module.main

EDIT: Also is there any way of disabling the whole "gang" mechanic? Removing everything gang related in controller.js doesn't seem to work, it still wants me to grind to -54k karma

**Comment by Hyrotos** [comment]
Hi,
can you look into the grow.js file on the n00dles Server and check if it's any different from the default one in this Repo?
That is my only guess, because it works perfectly for me, the arguments look correct and if it could not fit in RAM there would be a different Error Message.
If you encounter the error, you can also run the grow.js on that server with `run grow.js 102706.22572262463 the-hub 1640820219894` and check if that runs into this error.

For disabling the grinding for -54k karma, take a look in the [activityObserver.js](https://github.com/jenheilemann/bitburner-scripts/blob/2cbd8ebbe1ca67552bf3cfb3d6778fcd61ebabb4/src/satellites/activityObserver.js#L31-L34) and simply comment these lines out.

**Comment by AIT-OLPE** [comment]
The grow/hack/weaken looks exactly the same 

/**
 * @param {NS} ns
 */
export async function main(ns) {
  await ns.sleep(ns.args[0])
  await ns.grow(ns.args[1])
}


I think the issue solved itself though. As I said most of the scripts still worked so I left it running during the night and just ignored all the error messages for the ones that didn't work. Came up in the morning and reloaded the application and re-run the startup/run.js and no errors. I see though that it upgraded the RAM about 4 times so it may have been some sort of RAM overflow error.

**Comment by Hyrotos** [comment]
Good to hear that it somehow resolved itself, but I still find it strange, because for all that I know the game only check for RAM requirements when you try to run a script and fails in case there is not enough.
The error you posted also leads into a different direction.
And if you looked into the file after you rerun the startup/run.js script, it should already be replaced with the one on home, because the zombify function updated these files on all remote servers.

**Comment by AIT-OLPE** [comment]
The grow/hack/weaken script was exactly the same on my Home and on the machine and on github. Both before and after the "errors". As I said it worked, I mean the grow/hack/weaken worked on ALL machines. It seemed like it tried to start more EXECs than the RAM could handle though and those extra EXECs were giving me the error.

**Comment by jenheilemann** [comment]
There may have been something happening in satellites/hackerObserver.js that caused the error you saw. There will be lots of yellow and sometimes red alerts/toast messages caused by low RAM on a new startup, pretty unavoidable, but those are not runtime errors so much as warnings provided by the system. 

I have not encountered errors like the ones you're seeing, and I started a new BN this morning. LMK if you run into it again or figure out what caused it!
